---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    espresso:
      hosts:
        ts.validator.espresso.mainnet.encapsulate.xyz:
          type: validator
